<html>
  <head>
    <title>Just say no to the Audi A1 | Preventing normal people looking like cocks from a business park</title>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="style.css" />
  </head>
  <body>
    <div class="tagline"><?php echo $tagline?></div>
    <div class="answer" ><?php echo $answer; ?></div>
  </body>
</html>
